# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_sms_sender.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.change_but = QtWidgets.QPushButton(self.centralwidget)
        self.change_but.setGeometry(QtCore.QRect(890, 120, 71, 51))
        self.change_but.setObjectName("change_but")
        self.hide_but = QtWidgets.QPushButton(self.centralwidget)
        self.hide_but.setGeometry(QtCore.QRect(890, 180, 71, 51))
        self.hide_but.setObjectName("hide_but")
        self.stop_but = QtWidgets.QPushButton(self.centralwidget)
        self.stop_but.setGeometry(QtCore.QRect(880, 620, 71, 51))
        self.stop_but.setObjectName("stop_but")
        self.stack_Window = QtWidgets.QStackedWidget(self.centralwidget)
        self.stack_Window.setGeometry(QtCore.QRect(20, 60, 821, 631))
        self.stack_Window.setObjectName("stack_Window")
        self.send_window = QtWidgets.QWidget()
        self.send_window.setObjectName("send_window")
        self.line_phone = QtWidgets.QLineEdit(self.send_window)
        self.line_phone.setGeometry(QtCore.QRect(110, 30, 481, 31))
        self.line_phone.setObjectName("line_phone")
        self.line_message = QtWidgets.QLineEdit(self.send_window)
        self.line_message.setGeometry(QtCore.QRect(110, 100, 481, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_message.setFont(font)
        self.line_message.setText("")
        self.line_message.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.line_message.setObjectName("line_message")
        self.label_phone = QtWidgets.QLabel(self.send_window)
        self.label_phone.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.label_phone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_phone.setObjectName("label_phone")
        self.label_message = QtWidgets.QLabel(self.send_window)
        self.label_message.setGeometry(QtCore.QRect(30, 100, 61, 31))
        self.label_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_message.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_message.setObjectName("label_message")
        self.label_status = QtWidgets.QLabel(self.send_window)
        self.label_status.setGeometry(QtCore.QRect(30, 590, 371, 31))
        self.label_status.setObjectName("label_status")
        self.stack_Window.addWidget(self.send_window)
        self.log_window = QtWidgets.QWidget()
        self.log_window.setObjectName("log_window")
        self.scrollArea = QtWidgets.QScrollArea(self.log_window)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 101, 631))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 99, 629))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.log_window)
        self.scrollArea_2.setGeometry(QtCore.QRect(110, 0, 711, 631))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 629))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stack_Window.addWidget(self.log_window)
        self.title_lab = QtWidgets.QLabel(self.centralwidget)
        self.title_lab.setGeometry(QtCore.QRect(20, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.start_but = QtWidgets.QPushButton(self.centralwidget)
        self.start_but.setGeometry(QtCore.QRect(890, 60, 71, 51))
        self.start_but.setObjectName("start_but")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack_Window.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_but.setText(_translate("MainWindow", "Change"))
        self.hide_but.setText(_translate("MainWindow", "Hide"))
        self.stop_but.setText(_translate("MainWindow", "Stop"))
        self.line_phone.setText(_translate("MainWindow", "+79991112233"))
        self.label_phone.setText(_translate("MainWindow", "Phone"))
        self.label_message.setText(_translate("MainWindow", "Message"))
        self.label_status.setText(_translate("MainWindow", "status:"))
        self.title_lab.setText(_translate("MainWindow", "VIG sms sender"))
        self.start_but.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
